version: '3.8'

services:
    postgres:
        image: postgres:15.2
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: orders
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres_data:
