services:
    full-application:
        image: dhinojosa/full-application:${FULL_APPLICATION_VERSION:-1.0-SNAPSHOT}
        ports:
            - "8080:8080" # This is optional if HTTP port usage is removed
        depends_on:
            - postgres
        environment:
            DATABASE_URL: jdbc:postgresql://postgres:5432/orders
            DATABASE_USERNAME: postgres
            DATABASE_PASSWORD: postgres

    postgres:
        image: postgres:15.2
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: orders
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres_data:
